<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-02-26T10:24:19Z" name="Suite" finished-at="2025-02-26T10:24:43Z" duration-ms="24460">
    <groups>
      <group name="Sample">
        <method signature="SubmitOrder.ValidatedOrderConfirmation(java.util.HashMap)[pri:0, instance:rahulShettyacademy_ActualProject.SubmitOrder@2453f95d]" name="ValidatedOrderConfirmation" class="rahulShettyacademy_ActualProject.SubmitOrder"/>
      </group> <!-- Sample -->
      <group name="Regression">
        <method signature="ErrorValidationsTest.ValidatedOrderConfirmation()[pri:0, instance:rahulShettyacademy_ActualProject.ErrorValidationsTest@5b408dc3]" name="ValidatedOrderConfirmation" class="rahulShettyacademy_ActualProject.ErrorValidationsTest"/>
      </group> <!-- Regression -->
      <group name="Smoke">
        <method signature="ErrorValidationsTest.LoginErrorValidation()[pri:0, instance:rahulShettyacademy_ActualProject.ErrorValidationsTest@5b408dc3]" name="LoginErrorValidation" class="rahulShettyacademy_ActualProject.ErrorValidationsTest"/>
      </group> <!-- Smoke -->
    </groups>
    <test started-at="2025-02-26T10:24:19Z" name="SubmitOrder Test" finished-at="2025-02-26T10:24:29Z" duration-ms="9783">
      <class name="rahulShettyacademy_ActualProject.SubmitOrder">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:rahulShettyacademy_ActualProject.SubmitOrder@2453f95d]" started-at="2025-02-26T10:24:19Z" name="launchApplication" finished-at="2025-02-26T10:24:21Z" duration-ms="1896" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ValidatedOrderConfirmation(java.util.HashMap)[pri:0, instance:rahulShettyacademy_ActualProject.SubmitOrder@2453f95d]" started-at="2025-02-26T10:24:21Z" name="ValidatedOrderConfirmation" data-provider="getData" finished-at="2025-02-26T10:24:27Z" duration-ms="5519" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{product=ZARA COAT 3, pass=Deepak@95, email=johndeepak444@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidatedOrderConfirmation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:rahulShettyacademy_ActualProject.SubmitOrder@2453f95d]" started-at="2025-02-26T10:24:27Z" name="tearDown" finished-at="2025-02-26T10:24:27Z" duration-ms="98" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:rahulShettyacademy_ActualProject.SubmitOrder@2453f95d]" started-at="2025-02-26T10:24:27Z" name="launchApplication" finished-at="2025-02-26T10:24:28Z" duration-ms="1521" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OrderHisToryTest()[pri:0, instance:rahulShettyacademy_ActualProject.SubmitOrder@2453f95d]" started-at="2025-02-26T10:24:28Z" name="OrderHisToryTest" finished-at="2025-02-26T10:24:29Z" depends-on-methods="rahulShettyacademy_ActualProject.SubmitOrder.ValidatedOrderConfirmation" duration-ms="499" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHisToryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:rahulShettyacademy_ActualProject.SubmitOrder@2453f95d]" started-at="2025-02-26T10:24:29Z" name="tearDown" finished-at="2025-02-26T10:24:29Z" duration-ms="84" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- rahulShettyacademy_ActualProject.SubmitOrder -->
    </test> <!-- SubmitOrder Test -->
    <test started-at="2025-02-26T10:24:29Z" name="ErrorValidations Test" finished-at="2025-02-26T10:24:43Z" duration-ms="14448">
      <class name="rahulShettyacademy_ActualProject.ErrorValidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:rahulShettyacademy_ActualProject.ErrorValidationsTest@5b408dc3]" started-at="2025-02-26T10:24:29Z" name="launchApplication" finished-at="2025-02-26T10:24:30Z" duration-ms="1460" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:rahulShettyacademy_ActualProject.ErrorValidationsTest@5b408dc3]" started-at="2025-02-26T10:24:30Z" name="LoginErrorValidation" finished-at="2025-02-26T10:24:31Z" duration-ms="325" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Matching expected [Incorrect email or  password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Matching expected [Incorrect email or  password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at rahulShettyacademy_ActualProject.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:rahulShettyacademy_ActualProject.ErrorValidationsTest@5b408dc3]" started-at="2025-02-26T10:24:31Z" name="tearDown" finished-at="2025-02-26T10:24:31Z" duration-ms="97" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:rahulShettyacademy_ActualProject.ErrorValidationsTest@5b408dc3]" started-at="2025-02-26T10:24:31Z" name="launchApplication" finished-at="2025-02-26T10:24:34Z" duration-ms="3385" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:rahulShettyacademy_ActualProject.ErrorValidationsTest@5b408dc3]" started-at="2025-02-26T10:24:34Z" name="LoginErrorValidation" finished-at="2025-02-26T10:24:35Z" duration-ms="848" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Matching expected [Incorrect email or  password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Matching expected [Incorrect email or  password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at rahulShettyacademy_ActualProject.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:rahulShettyacademy_ActualProject.ErrorValidationsTest@5b408dc3]" started-at="2025-02-26T10:24:35Z" name="tearDown" finished-at="2025-02-26T10:24:36Z" duration-ms="96" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:rahulShettyacademy_ActualProject.ErrorValidationsTest@5b408dc3]" started-at="2025-02-26T10:24:36Z" name="launchApplication" finished-at="2025-02-26T10:24:40Z" duration-ms="4009" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ValidatedOrderConfirmation()[pri:0, instance:rahulShettyacademy_ActualProject.ErrorValidationsTest@5b408dc3]" started-at="2025-02-26T10:24:40Z" name="ValidatedOrderConfirmation" finished-at="2025-02-26T10:24:43Z" duration-ms="3759" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidatedOrderConfirmation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:rahulShettyacademy_ActualProject.ErrorValidationsTest@5b408dc3]" started-at="2025-02-26T10:24:43Z" name="tearDown" finished-at="2025-02-26T10:24:43Z" duration-ms="94" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- rahulShettyacademy_ActualProject.ErrorValidationsTest -->
    </test> <!-- ErrorValidations Test -->
  </suite> <!-- Suite -->
</testng-results>
